version: '1.2.0'
systemName: 'rwhservers'
name: 'Products Reseller Server'
description: 'Rad Web Hosting Module Framework.<br>For more info visit our <a href="https://radwebhosting.com/client_area/knowledgebase/582/Install-PAYG-Reseller-WHMCS-Module.html" style="color: #4169E1;" target="_blank">Docs</a>.'
clientareaName: 'rwhservers'
author: '<a href="https://radwebhosting.com" targer="_blank">Rad Web Hosting</a>'
moduleIcon: 'ip_manager'
